#!/bin/bash
#
# Copyright (c) 2016 by Cisco Systems, Inc.
# All rights reserved.
#

declare module_name
declare puppet_path="/opt/puppetlabs/bin"

function die() {
  printf "Error: %s\n" "$@" >&2
  exit 1
}

function parse_args() {
  if [ "$#" -ne 1 ]; then
    die "Expected arguments: module_name"
  fi
  module_name="$1"
}

function set_puppet_path() {
  if [ -f /usr/bin/puppet ]; then
    puppet_path="/usr/bin"
  fi
}

function main() {
  parse_args "$@"
  set_puppet_path
  $puppet_path/puppet apply -ve "include $module_name" --detailed-exitcodes; rc=$?

  # Detailed exit code from puppet apply:
  #
  # - an exit code of '2' means there were changes
  # - an exit code of '4' means there were failures during the transaction
  # - an exit code of '6' means there were both changes and failures.
  #
  [ $rc -eq 2 ] && return 0
  return $rc
}

main "$@"
