#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function profile {
	echo "$(date)[$SECONDS]: $1"
}

function manage_service() {
	local service=$1
	local -r action=$2
	service=${service%.service}

	if [[ ${service} == "monit" && ${action,,} == "reload" ]]; then
		profile "Performing $action on ${service}"
		monit reload
		exit $?
	fi

	if [[ -z "$action" ]]; then
		echo "Unable to find appropriate action in args [$@]. Bailing out!"
		exit 1
	elif [[ "${action,,}" != "start" &&
			"${action,,}" != "stop" &&
			"${action,,}" != "restart" ]]; then
		echo "Invalid action [${action,,}]. Only 'start', 'stop', 'restart' or 'monit reload' allowed. Bailing out!"
		exit 1
	fi

	profile "Performing $action on ${service}"

	if [[ -x "/usr/sbin/service" ]]; then
		/usr/sbin/service ${service} ${action}
	elif [[ -x "/usr/sbin/systemctl" ]]; then
		/usr/sbin/systemctl ${action} ${service}.service
	elif [[ -x "/sbin/service" ]]; then
		/sbin/service ${service} ${action}
	else
		echo "Unknown service manager (neither systemctl nor service). Bailing out."
		exit 1
	fi
}

function main() {
	manage_service $@
}

set +x
if [ "$debug" = "yes" ]; then
	set -x
fi
main "$@"
