#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
if [ "$debug" = "yes" ]; then
  set -x
fi

declare src_path=""
declare dest_path=""

declare -r mirror_server="mirror"

function die() {
  printf "Error: %s\n" "$@" >&2
  exit 1
}

function parse_args() {
  if [[ "$#" -gt 3 || "$#" -lt 2 ]]; then
    die "Expected arguments: pkg_name dst_dir [servertype]"
  fi

  local pkg_name="$1"
  local dst_dir="$2"
  local servertype="$3"

  if [[ $servertype == "" ]]; then
    src_path="/var/www/mirror/puppet-modules/puppet-aide"
  else
    src_path="/var/www/mirror/servertype/$servertype"
  fi

  pkg_type="${pkg_name:$((${#pkg_name}-3))}"
  if [ "$pkg_type" = "deb" ]; then
    src_path="$src_path/pool/main/$pkg_name"
  elif [ "$pkg_type" = "rpm" ]; then
    src_path="$src_path/$pkg_name"
  else
    die "Unknown package type for $pkg_name"
  fi

  if [ ! -d $dst_dir ]; then
    die "The package destination $dst_dir is not a directory"
  fi
  dst_path="$dst_dir/$pkg_name"
}

function main() {
  parse_args "$@"
  scp -q $mirror_server:$src_path $dst_path
}

main "$@"
