#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
set -x

declare dst_dir=""
declare src_path=""
declare packages_file=""

declare -r mirror_dir="/var/www/mirror"
declare -r mirror_server="mirror"


function die() {
  printf "Error: %s\n" "$@" >&2
  exit 1
}

function parse_args() {
  if [ "$#" -ne 3 ]; then
    die "Expected arguments: servertype version dst_dir"
  fi
  local servertype="$1"
  local version="$2"
  dst_dir="$3"

  if [ ! -d $dst_dir ]; then
    die "The package destination $dst_dir is not a directory"
  fi
  src_path="$mirror_dir/servertype/$servertype"
  packages_file="packages-${version}.txt"
}

function copy_packages_file() {
  scp -q $mirror_server:$src_path/$packages_file $dst_dir/$packages_file

  # If the packages file doesn't exist, we are done, no big deal.
  if [ ! -r $dst_dir/$packages_file ]; then
    exit 0
  fi
}

function copy_packages() {
  cat $dst_dir/$packages_file | while read pkg; do
  scp -q $mirror_server:$src_path/$pkg $dst_dir/$pkg
  done
}

function main() {
  parse_args "$@"
  copy_packages_file
  copy_packages
}

main "$@"
