#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

go get -u github.com/client9/misspell/cmd/misspell

declare -r aws_sdk_dir="vendor/github.com/aws/aws-sdk-go"
rm -rf $aws_sdk_dir
git submodule init $aws_sdk_dir
git submodule update $aws_sdk_dir

declare -r cisco_spark_dir="vendor/github.com/jbogarin/go-cisco-spark"
rm -rf $cisco_spark_dir
git submodule init $cisco_spark_dir
git submodule update $cisco_spark_dir

declare -r xcrypto_dir="vendor/golang.org/x/crypto"
rm -rf $xcrypto_dir
git submodule init $xcrypto_dir
git submodule update $xcrypto_dir

declare -r querystring_dir="vendor/github.com/google/go-querystring"
rm -rf $querystring_dir
git submodule init $querystring_dir
git submodule update $querystring_dir
