#!/bin/bash
#
# Copyright (c) 2017 by Cisco Systems, Inc.
# All rights reserved.
#
source "/usr/lib/arc/arc.sh"

declare mount_point=""

function parse_args() {
  if [ "$#" -lt 1 ]; then
    die "Expected arguments: user [remove]"
  fi
  mount_point="$1"
}

function main() {
  parse_args "$@"
  /bin/umount -f $mount_point
  return $success
}

main "$@"
