#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
source "/usr/lib/arc/arc.sh"

declare user=""
declare ssh_dir
declare auth_file

declare tmp_auth_file

function parse_args() {
  if [ "$#" -ne 1 ]; then
    die "Expected arguments: user"
  fi
  user="$1"
  ssh_dir="/home/$user/.ssh"
  tmp_auth_file="/tmp/authorized_keys.$user"
  auth_file="$ssh_dir/authorized_keys"
}

function setup() {
  if ! user_exists $user; then
    return
  fi

  if [ ! -f $tmp_auth_file ]; then
    die "Cannot find $tmp_auth_file"
  fi

  rm -rf $ssh_dir
  mkdir $ssh_dir
  chown $user:$user $ssh_dir
  chmod 700 $ssh_dir

  mv $tmp_auth_file $auth_file
  chown $user:$user $auth_file
  chmod 600 $auth_file
}

function main() {
  parse_args "$@"
  setup
}

main "$@"
