#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
source "/usr/lib/arc/arc.sh"

declare user=""
declare remove=""

declare sudo_file=""

function parse_args() {
  if [ "$#" -lt 1 ]; then
    die "Expected arguments: user [remove]"
  fi
  user="$1"
  if [[ "$2" == "remove" ]]; then
    remove="yes"
  fi

  sudo_file="/etc/sudoers.d/$user"
}

function sudo_create() {
  if ! user_exists $user; then
    return
  fi

  echo "$user ALL=(ALL)    NOPASSWD: ALL" > $sudo_file
  chown root:root $sudo_file
  chmod 440 $sudo_file
}

function sudo_remove() {
  rm -f $sudo_file
}

function main() {
  parse_args "$@"
  if [[ "$remove" == "yes" ]]; then
    sudo_remove
  else
    sudo_create
  fi
}

main "$@"
