#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
source "/usr/lib/arc/arc.sh"

declare install_cmd=""
declare upgrade_cmd=""
declare manifest=""
declare pkg_type=""
declare first_package=""

function parse_args() {
  if [ "$#" -ne 1 ]; then
    die "Expected arguments: manifest"
  fi

  manifest="$1"
  first_package=$(head -n 1 $manifest)
  pkg_type="${first_package:$((${#first_package}-3))}"
  if [ "$pkg_type" = "deb" ]; then
    install_cmd="dpkg -i"
  elif [ "$pkg_type" = "rpm" ]; then
    install_cmd="yum install -y"
    upgrade_cmd="yum upgrade -y"
  else
    die "Unknown package type for $pkg_name"
  fi
}

function upgrade() {
  $upgrade_cmd $(cat $manifest)
}

function install() {
  $install_cmd $(cat $manifest)
}

function installed() {
  while read package; do
    local output="$(rpm -qa $(rpm -qp --queryformat '%{NAME}' "$package"))"
    if [ "$output" = "" ]; then
      return 1
    fi
  done <$manifest
  return 0
}

function main() {
  parse_args "$@"

  cd "/usr/lib/arc/"
  if [ "$pkg_type" = "deb" ]; then
    install
    return $?
  fi

  if ! installed; then
    install
    return $?
  fi

  upgrade
  return $?
}

main "$@"
