#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
source "/usr/lib/arc/arc.sh"

# Parameters
declare device=""
declare mount_point=""
declare fs_type=""
declare skip_format=""
declare -i inodes=0

# Discovered
declare aws_device=""
declare uuid=""

function parse_args() {
  if [[ $# -lt 4 ]]; then
    die "device mount_point fs_type expected"
  fi
  device="$1"
  mount_point="$2"
  fs_type="$3"
  inodes=$4
  skip_format="$5"
}

function a2n() {
  local -A n
  n=([a]=0 [b]=1 [c]=2 [d]=3 [e]=4 [f]=5 [g]=6 [h]=7 [i]=8 [j]=9)
  echo -n ${n[$1]}
}

function get_aws_nvme_device() {
  aws_device="/dev/nvme$(a2n ${device/\/dev\/sd/})n1"
  if [[ ! -b $aws_device ]]; then
    die "Cannot find block device $aws_device"
  fi
}

function get_aws_device() {
  aws_device="/dev/xvd${device/\/dev\/sd/}"
  if [[ ! -b $aws_device ]]; then
    get_aws_nvme_device
  fi
}

function format_device() {
  if [[ "$skip_format" == "skip_format" ]]; then
    return
  fi
  if [[ "$fs_type" == "xfs" ]]; then
    mkfs.xfs -n ftype=1 $aws_device
  elif [[ "$fs_type" == "ext4" && $inodes -gt 0 ]]; then
    mkfs.ext4 -N $inodes $aws_device
  elif ! mkfs -t $fs_type $aws_device; then
    die "Failed to format device $aws_device as $fs_type"
  fi
}

function create_mount_point() {
  if [[ -d $mount_point ]]; then
    return
  fi
  if [[ -L $mount_point && -d "$(readlink -f $mount_point)" ]]; then
    return
  fi
  if ! mkdir -p $mount_point; then
    die "Failed to create mount point $mount_point"
  fi
}

function mount_device() {
  if ! mount $aws_device $mount_point; then
    die "Failed to mount device $aws_device to $mount_point"
  fi
  count=0
  while ! grep -q $aws_device /etc/mtab; do
    sleep 5
    (( count ++))
    if [ $count -eq 12 ]; then
      die "Failed to detect mount of $aws_device"
    fi
  done
}

function get_uuid() {
  uuid=$(blkid "$aws_device" -sUUID -ovalue)
  if [[ -n "${uuid}" ]]; then
    return
  fi
  die "Failed to find the uuid of device $aws_device"
}

function umount_device() {
  if ! umount $mount_point; then
    die "Failed to umount $mount_point"
  fi
}

function modify_fstab() {
  local entry="UUID=$uuid  $mount_point  $fs_type  defaults  0 2"
  if egrep -q "^UUID=$uuid" /etc/fstab; then
    return
  fi
  echo "$entry" >> /etc/fstab
}

function mount_all() {
  if ! mount -a; then
    die "Failed to mount"
  fi
}

function main() {
  parse_args "$@"
  get_aws_device
  format_device
  create_mount_point
  mount_device
  get_uuid
  umount_device
  modify_fstab
  mount_all
}

main "$@"
