#!/bin/bash
#
# Copyright (c) 2016 by Cisco Systems, Inc.
# All rights reserved.
#

declare ID="centos"
declare VERSION_ID="6"
if [[ -r /etc/os-release ]]; then
  source /etc/os-release
fi

# Centos7 runs a systemd-hostnamed service to automatically update hostname.
# The value it gets is from the DC, if available (e.g. AWS defines a private
# DNS for each instance on creation). This can happen before or at the same
# time as we run this script, so, we delay here a bit to let that service
# run and then we continue defining our own hostname.
#
# TODO: Figure out a better way here if possible.
if [[ "$ID" = "centos" && "$VERSION_ID" = "7" ]]; then
  sleep 15
fi

declare fqdn=""

function die() {
  printf "Error: %s\n" "$@"
  exit 1
}

function parse_args() {
  if [[ $# -ne 1 ]]; then
    die "fqdn expected"
  fi
  fqdn="$1"
}

function setup_runtime() {
  hostname $fqdn
}

function setup_etc_hostname() {
  local etc_hostname="/etc/hostname"
  if [[ -f /etc/hostname ]]; then
    echo "$fqdn" > $etc_hostname
  fi
}

function setup_cloud_cfg() {
  local dir="/etc/cloud/cloud.cfg.d"
  if [[ -d "$dir" ]]; then
    echo "hostname: $fqdn" > "$dir/hostname.cfg"
  fi
}

function setup_network() {
  if [[ "$ID" != "centos" ]]; then
    return
  fi
  local network="/etc/sysconfig/network"
  if egrep "^HOSTNAME=" $network >/dev/null  2>&1; then
    sed -i'.orig' "s/^HOSTNAME=.*\$/HOSTNAME=$fqdn/" $network
  else
    echo "HOSTNAME=$fqdn" >> $network
  fi
}

function main() {
  parse_args "$@"
  if ! setup_runtime; then
    die "Failed to setup runtime hostname"
  fi
  setup_etc_hostname
  setup_cloud_cfg
  if ! setup_network; then
    die "Failed to setup /etc/sysconfig/network"
  fi
  return 0
}

main "$@"
