#!/bin/bash
#
# Copyright (c) 2017, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
source "/usr/lib/arc/arc.sh"

declare user=""
declare arc_dir="/usr/lib/arc"

function create_arc_dir() {
  mkdir -p $arc_dir
}

function create_arc_subdirs() {
  local d
  local dirs="cassandra cloudfoundry consul create destroy elasticsearch graphite haproxy jenkins paging plugins provision redis repos sparkcall tools ucxn users"
  for d in $dirs; do
    if [ ! -d "$arc_dir/$d" ]; then
      rm -f $arc_dir/$d
    fi
    mkdir -p $arc_dir/$d
  done
}

function fix_permissions() {
  group=$user
  if $(getent group platform &>/dev/null); then
    group=platform
  fi
  chown -R $user:$group $arc_dir
  chmod -R 770 $arc_dir
}

function save_setup() {
  if [[ "$0" = "/tmp/setup_arc" ]]; then
    mv -f "$0" "$arc_dir"
    chown $user:$group $arc_dir/setup_arc
    chmod 770 $arc_dir/setup_arc
  fi
}

function main() {
  if [[ -z "$SUDO_USER" ]]; then
    die "Must be run under sudo"
    return 1
  fi
  user="$SUDO_USER"
  create_arc_dir
  create_arc_subdirs
  fix_permissions
  save_setup
}

main "$@"
