#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function main()
{
  local macs
  macs="hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"

  local ciphers
  ciphers="chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"

  local client_alive_interval
  client_alive_interval=21600

  local client_alive_count_max
  client_alive_count_max=0

  # Restrict access to /etc/ssh/sshd_config
  chmod 600 /etc/ssh/sshd_config
  chown root:root /etc/ssh/sshd_config

  # Modify /etc/ssh/sshd_config
  sed -i -e 's/^#*Protocol 2/Protocol 2/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*LogLevel [A-Z]/LogLevel INFO/g' /etc/ssh/sshd_config
  sed -i -e 's/^X11Forwarding yes/X11Forwarding no/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*MaxAuthTries [0-9]*/MaxAuthTries 4/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*IgnoreRhosts.*$/IgnoreRhosts yes/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*HostbasedAuthentication .*/HostbasedAuthentication no/g' /etc/ssh/sshd_config
  sed -i -e 's/#*PermitRootLogin.*$/PermitRootLogin no/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*PermitEmptyPasswords .*/PermitEmptyPasswords no/g' /etc/ssh/sshd_config
  sed -i -e 's/^#*PermitUserEnvironment .*/PermitUserEnvironment no/g' /etc/ssh/sshd_config
  sed -i -e "s/^#*ClientAliveInterval [0-9][0-9]*/ClientAliveInterval $client_alive_interval/g" /etc/ssh/sshd_config
  sed -i -e "s/^#*ClientAliveCountMax [0-9][0-9]*/ClientAliveCountMax $client_alive_count_max/g" /etc/ssh/sshd_config
  if [ $(grep "MACs" /etc/ssh/sshd_config | wc -l) -eq 0 ]; then
    echo $'\n' >> /etc/ssh/sshd_config
    echo "MACs $macs" >> /etc/ssh/sshd_config
  else
    sed -i -e "s/^MACs.*$/MACs $macs/g" /etc/ssh/sshd_config
  fi
  if [ $(grep "^Ciphers" /etc/ssh/sshd_config | wc -l) -eq 0 ]; then
    echo $'\n' >> /etc/ssh/sshd_config
    echo "Ciphers $ciphers" >> /etc/ssh/sshd_config
  else
    sed -i -e "s/^Ciphers.*$/Ciphers $ciphers/g" /etc/ssh/sshd_config
  fi
}

main "$@"
