#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

source ../arc.sh

function main() {
  # Ensure directory permissions are configured
  chmod 600 /etc/crontab
  chmod 600 /etc/cron.hourly
  chmod 600 /etc/cron.daily
  chmod 600 /etc/cron.weekly
  chmod 600 /etc/cron.monthly
  chmod 600 /etc/cron.d

  # Remove cron.deny, at.deny & anacron.deny
  rm -f /etc/cron.deny
  rm -f /etc/at.deny
  rm -f /etc/anacron.deny

  if [[ $ID == "centos" ]]; then
    if [ $(systemctl is-enabled crond) != "enabled" ]; then
      systemctl enable crond
    fi
  elif [[ $(grep -i "start on runlevel [2345]" /etc/init/cron.conf | wc -l) -ne 1 ]]; then
    sed -i -e 's/start on runlevel \[.*\]/start on runlevel [2345]/g' /etc/init/cron.conf
  fi
}

main "$@"
