#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

source $(dirname $0)/cli.sh

run_err arc cli instance
run_err arc cli instance help
run_err arc cli instance info
run_err arc cli instance config
run_err arc cli instance create
run_err arc cli instance foobar

run arc cli instance bastion-01 help
run arc cli instance bastion-01 config
run arc cli instance bastion-01 info
run arc cli instance bastion-01 create test
run arc cli instance bastion-01 provision test
run arc cli instance bastion-01 stop test
run arc cli instance bastion-01 start test
run arc cli instance bastion-01 restart test
run arc cli instance bastion-01 replace test
run arc cli instance bastion-01 destroy test

run_err arc cli instance bastion-01
run_err arc cli instance bastion-01 foobar
run_err arc cli instance bastion-01 foobar create


run_err arc cli cluster core instance
run_err arc cli cluster core instance help
run_err arc cli cluster core instance config
run_err arc cli cluster core instance create
run_err arc cli cluster core instance bastion-01
run_err arc cli cluster core instance bastion-01 help


run_err arc cli cluster core pod bastion instance
run_err arc cli cluster core pod bastion instance help
run_err arc cli cluster core pod bastion instance config
run_err arc cli cluster core pod bastion instance create

run_err arc cli cluster core pod bastion instance bastion foobar

run arc cli cluster core pod bastion instance bastion-01 help
run arc cli cluster core pod bastion instance bastion-01 config
run arc cli cluster core pod bastion instance bastion-01 info
run arc cli cluster core pod bastion instance bastion-01 create test
run arc cli cluster core pod bastion instance bastion-01 provision test
run arc cli cluster core pod bastion instance bastion-01 stop test
run arc cli cluster core pod bastion instance bastion-01 start test
run arc cli cluster core pod bastion instance bastion-01 restart test
run arc cli cluster core pod bastion instance bastion-01 replace test
run arc cli cluster core pod bastion instance bastion-01 destroy test

run_err arc cli cluster core pod bastion instance bastion-01
run_err arc cli cluster core pod bastion instance bastion-01 foobar
run_err arc cli cluster core pod bastion instance bastion-01 foobar create
