#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

source $(dirname $0)/cli.sh

run_err arc cli pod
run_err arc cli pod help
run_err arc cli pod info
run_err arc cli pod config
run_err arc cli pod create
run_err arc cli pod foobar

run_err arc cli cluster core pod
run_err arc cli cluster core pod help
run_err arc cli cluster core pod config
run_err arc cli cluster core pod create

run_err arc cli cluster core pod bastion foobar

run arc cli cluster core pod bastion help
run arc cli cluster core pod bastion config
run arc cli cluster core pod bastion info
run arc cli cluster core pod bastion create test
run arc cli cluster core pod bastion provision test
run arc cli cluster core pod bastion stop test
run arc cli cluster core pod bastion start test
run arc cli cluster core pod bastion restart test
run arc cli cluster core pod bastion replace test
run arc cli cluster core pod bastion destroy test

run_err arc cli cluster core pod bastion
run_err arc cli cluster core pod bastion foobar
run_err arc cli cluster core pod bastion foobar create

run arc cli pod bastion help
run arc cli pod bastion config
run arc cli pod bastion info
run arc cli pod bastion create test
run arc cli pod bastion provision test
run arc cli pod bastion stop test
run arc cli pod bastion start test
run arc cli pod bastion restart test
run arc cli pod bastion replace test
run arc cli pod bastion destroy test

run_err arc cli pod bastion
run_err arc cli pod bastion foobar
run_err arc cli pod bastion foobar create

