#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

source $(dirname $0)/cli.sh

run arc cli network secgroup help
run arc cli network secgroup config
run arc cli network secgroup info
run arc cli network secgroup create test
run arc cli network secgroup update test
run arc cli network secgroup destroy test

run_err arc cli network secgroup
run_err arc cli network secgroup foobar
run_err arc cli network secgroup foobar create
 
run arc cli secgroup help
run arc cli secgroup config
run arc cli secgroup info
run arc cli secgroup create test
run arc cli secgroup update test
run arc cli secgroup destroy test

run_err arc cli secgroup
run_err arc cli secgroup foobar
run_err arc cli secgroup foobar update

run arc cli network secgroup common help
run arc cli network secgroup common config
run arc cli network secgroup common info
run arc cli network secgroup common create test
run arc cli network secgroup common update test
run arc cli network secgroup common destroy test

run_err arc cli network secgroup common
run_err arc cli network secgroup common foobar
run_err arc cli network secgroup common foobar create

run arc cli secgroup common help
run arc cli secgroup common config
run arc cli secgroup common info
run arc cli secgroup common create test
run arc cli secgroup common update test
run arc cli secgroup common destroy test

run_err arc cli secgroup common
run_err arc cli network secgroup common foobar
run_err arc cli network secgroup common foobar create
