#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

source $(dirname $0)/cli.sh

run arc cli network subnet help
run arc cli network subnet config
run arc cli network subnet info
run arc cli network subnet create test
run arc cli network subnet destroy test

run_err arc cli network subnet
run_err arc cli network subnet foobar
run_err arc cli network subnet foobar create
 
run arc cli subnet help
run arc cli subnet config
run arc cli subnet info
run arc cli subnet create test
run arc cli subnet destroy test

run_err arc cli subnet
run_err arc cli network subnet foobar
run_err arc cli network subnet foobar create

run arc cli network subnet bastion help
run arc cli network subnet bastion config
run arc cli network subnet bastion info
run arc cli network subnet bastion create test
run arc cli network subnet bastion destroy test

run_err arc cli network subnet bastion
run_err arc cli network subnet bastion foobar
run_err arc cli network subnet bastion foobar create

run arc cli subnet bastion help
run arc cli subnet bastion config
run arc cli subnet bastion info
run arc cli subnet bastion create test
run arc cli subnet bastion destroy test

run_err arc cli subnet bastion
run_err arc cli subnet bastion foobar
run_err arc cli subnet bastion foobar create
